#----------------------------------------------------------------------------
#       Make Workspace
#
# 
#
# This file was generated by MPC.  Any changes made directly to
# this file will be lost the next time it is generated.
#
# MPC Command:
# /home/alistenberger/MPC/MPC/mwc.pl -type make
#
#----------------------------------------------------------------------------


all: shortestPath

depend: shortestPath-depend

clean generated realclean check-syntax $(CUSTOM_TARGETS):
	@$(MAKE) -f Makefile.shortestPath $(@)

.PHONY: shortestPath
shortestPath:
	@$(MAKE) -f Makefile.shortestPath all

.PHONY: shortestPath-depend
shortestPath-depend:
	@$(MAKE) -f Makefile.shortestPath depend

project_name_list:
	@echo shortestPath
